uvicorn-log-level: "info"
kv-cache-dtype: auto

# "pass_config":{"enable_fi_allreduce_fusion":true}, -> leads to error
compilation-config: '{
    "pass_config": {"enable_noop":true},
    "max_cudagraph_capture_size": 2048
}'

# async-scheduling: true

no-enable-prefix-caching: true
max-num-batched-tokens: 8192
max-num-seqs: 256